In [1]:
# Install (only needed if not already installed)
!pip install scikit-learn

import numpy as np
import string

In [2]:
documents = [
    "The cat sat on the mat.",
    "The dog sat on the log.",
    "Cats and dogs are pets."
]

In [3]:
from sklearn.preprocessing import OneHotEncoder

words = [word.lower().strip(string.punctuation)
         for doc in documents for word in doc.split()]

vocabulary = sorted(set(words))

encoder = OneHotEncoder(sparse_output=False)
one_hot_vectors = encoder.fit_transform(np.array(vocabulary).reshape(-1, 1))

word_to_onehot = {
    vocabulary[i]: one_hot_vectors[i]
    for i in range(len(vocabulary))
}

for word, vector in word_to_onehot.items():
    print(f"{word}: {vector}")

and: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
are: [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
cat: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
cats: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
dog: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
dogs: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
log: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
mat: [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
on: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
pets: [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
sat: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
the: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [4]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(documents)

print("BoW Matrix:\n", X_bow.toarray())
print("Features:\n", vectorizer.get_feature_names_out())

BoW Matrix:
 [[0 0 1 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 0 0 0 1 0 0]]
Features:
 ['and' 'are' 'cat' 'cats' 'dog' 'dogs' 'log' 'mat' 'on' 'pets' 'sat' 'the']


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(documents)

print("TF-IDF Matrix:\n", X_tfidf.toarray())
print("Features:\n", tfidf_vectorizer.get_feature_names_out())

TF-IDF Matrix:
 [[0.         0.         0.42755362 0.         0.         0.
  0.         0.42755362 0.32516555 0.         0.32516555 0.6503311 ]
 [0.         0.         0.         0.         0.42755362 0.
  0.42755362 0.         0.32516555 0.         0.32516555 0.6503311 ]
 [0.4472136  0.4472136  0.         0.4472136  0.         0.4472136
  0.         0.         0.         0.4472136  0.         0.        ]]
Features:
 ['and' 'are' 'cat' 'cats' 'dog' 'dogs' 'log' 'mat' 'on' 'pets' 'sat' 'the']


In [6]:
count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(documents)

print("Count Vectorizer Matrix:\n", X_count.toarray())
print("Features:\n", count_vectorizer.get_feature_names_out())

Count Vectorizer Matrix:
 [[0 0 1 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 0 0 0 1 0 0]]
Features:
 ['and' 'are' 'cat' 'cats' 'dog' 'dogs' 'log' 'mat' 'on' 'pets' 'sat' 'the']


In [7]:
# Download small GloVe embeddings
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove.6B.zip

# Load embeddings
embeddings_index = {}
with open("glove.6B.50d.txt", encoding="utf8") as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], dtype='float32')
        embeddings_index[word] = vector

# Example
print("Vector for 'cat':\n", embeddings_index.get("cat"))

--2026-04-22 21:12:14--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2026-04-22 21:12:14--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2026-04-22 21:12:14--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glov